apiVersion: v1
kind: Pod
metadata:
  name: ausf
  namespace: {{ openshift.namespace }}
  labels:
    app: ausf
spec:
  {{ nodes.ausf.custom }}
  containers:
  - name: ausf
    image: "{{ nodes.ausf.image }}"
    command:
      - /free5gc/bin/./ausf
    ports:
      - containerPort: {{ nodes.ausf.port }}
    volumeMounts:
      - name: conf
        mountPath: /free5gc/config/ausfcfg.yaml
        subPath: ausfcfg.yaml
  volumes:
    - name: conf
      configMap:
        name: ausf-config
        items:
        - key: ausfcfg.yaml
          path: ausfcfg.yaml
