apiVersion: v1
kind: Pod
metadata:
  name: udr
  namespace: {{ openshift.namespace }}
  labels:
    app: udr
spec:
  {{ nodes.udr.custom }}
  containers:
  - name: udr
    image: {{ nodes.udr.image }}
    command:
      - /free5gc/bin/./udr
    ports:
      - containerPort: {{ nodes.udr.port }}
    volumeMounts:
      - name: conf
        mountPath: /free5gc/config/udrcfg.yaml
        subPath: udrcfg.yaml
  volumes:
    - name: conf
      configMap:
        name: udr-config
        items:
        - key: udrcfg.yaml
          path: udrcfg.yaml
