apiVersion: v1
kind: Pod
metadata:
  name: upf
  namespace: {{ openshift.namespace }}
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "net-pfcp", "ips": [ "{{ nodes.upf.pfcp.ip }}" ], "mac": "{{ nodes.upf.pfcp.mac }}"},
                                   { "name": "net-gtp", "ips": [ "{{ nodes.upf.gtp.ip }}" ], "mac": "{{ nodes.upf.gtp.mac }}"}]'
  labels:
    app: upf
spec:
  {{ nodes.upf.custom }}
  containers:
  - name: upf
    image: {{ nodes.upf.image }}
    command: ["/bin/sh", "-c" ]
    args:
      - dnf -y install iptables http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/tcpdump-4.9.3-1.el8.x86_64.rpm;
        iptables -A FORWARD -i eth0 -j ACCEPT;
        iptables -A FORWARD -i upfgtp -j ACCEPT;
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
        iptables -t nat -A POSTROUTING -o upfgtp -j MASQUERADE;
        /free5gc/NFs/upf/build/bin/free5gc-upfd -f /free5gc/NFs/upf/build/config/upfcfg.yaml
    volumeMounts:
      - name: conf
        mountPath: /free5gc/NFs/upf/build/config/upfcfg.yaml
        subPath: upfcfg.yaml
      - name: net
        mountPath: /dev/net
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
  volumes:
    - name: conf
      configMap:
        name: upf-config
        items:
        - key: upfcfg.yaml
          path: upfcfg.yaml
    - hostPath:
        path: /dev/net
        type: ""
      name: net
