apiVersion: v1
kind: Pod
metadata:
  name: webui
  namespace: {{ openshift.namespace }}
  labels:
    app: webui
spec:
  {{ nodes.webui.custom }}
  containers:
  - name: webui
    image: {{ nodes.webui.image }}
    command: ['go', 'run', 'server.go']
    env:
      - name: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
      - name: GOPATH
        value: /go
      - name: GOROOT
        value: /usr/local/go
    ports:
      - containerPort: 5000
    workingDir: /free5gc/webconsole
    volumeMounts:
      - name: conf
        mountPath: /free5gc/config/webuicfg.yaml
        subPath: webuicfg.yaml
  volumes:
    - name: conf
      configMap:
        name: webui-config
        items:
        - key: webuicfg.yaml
          path: webuicfg.yaml
