kind: Service
apiVersion: v1
metadata:
  name: mongo-svc
  namespace: {{ openshift.namespace }}
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    targetPort: {{ nodes.mongo.port }}
    port: {{ nodes.mongo.port }}

