apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-config
  namespace: {{ openshift.namespace }}
data:
  udrcfg.yaml: |
    info:
      version: 1.0.0
      description: UDR initial local configuration

    configuration:
      sbi: # Service-based interface information
        scheme: http # the protocol for sbi (http or https)
        registerIPv4: udr-svc # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        port: {{ nodes.udr.port }} # port used to bind the service
      mongodb:
        name: free5gc # Database name in MongoDB
        url: mongodb://mongo-svc:{{ nodes.mongo.port }} # URL of MongoDB
      nrfUri: http://nrf-svc:{{ nodes.nrf.port }} # a valid URI of NRF

    # the kind of log output
      # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
      # ReportCaller: enable the caller report or not, value: true or false
    logger:
      UDR:
        debugLevel: info
        ReportCaller: false
      MongoDBLibrary:
        debugLevel: info
        ReportCaller: false
      PathUtil:
        debugLevel: info
        ReportCaller: false
      OpenApi:
        debugLevel: info
        ReportCaller: false
