# 
# Undeploy AUSF
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Remove AUSF config map
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: ConfigMap
      name: ausf-config
      namespace: "{{ openshift.namespace }}"
      
  - name: Remove AUSF NF
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Pod
      name: ausf
      namespace: "{{ openshift.namespace }}"

  - name: Remove AUSF service
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Service
      name: ausf-svc
      namespace: "{{ openshift.namespace }}"

