# 
# Undeploy MongoDB
---

- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Remove MongoDB container
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Pod
      name: mongodb
      namespace: "{{ openshift.namespace }}"
      
  - name: Remove MongoDB service
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Service
      name: mongo-svc
      namespace: "{{ openshift.namespace }}"
