# 
# Undeploy UDM
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Remove UDM config map
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: ConfigMap
      name: udm-config
      namespace: "{{ openshift.namespace }}"
      
  - name: Remove UDM NF
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Pod
      name: udm
      namespace: "{{ openshift.namespace }}"

  - name: Remove UDM service
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Service
      name: udm-svc
      namespace: "{{ openshift.namespace }}"

