# 
# Undeploy UDR
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Remove UDR config map
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: ConfigMap
      name: udr-config
      namespace: "{{ openshift.namespace }}"
      
  - name: Remove UDR NF
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Pod
      name: udr
      namespace: "{{ openshift.namespace }}"

  - name: Remove UDR service
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Service
      name: udr-svc
      namespace: "{{ openshift.namespace }}"
