# 
# Undeploy UE simulator
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Remove UE Simulator config map
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: ConfigMap
      name: uesim-config
      namespace: "{{ openshift.namespace }}"
      
  - name: Remove UE simulator
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: Pod
      name: uesim
      namespace: "{{ openshift.namespace }}"
