# 
# Undeploy UPF
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Remove UPF config map
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: v1
      kind: ConfigMap
      name: upf-config
      namespace: "{{ openshift.namespace }}"
      
  - name: Remove UPF NF
    kubernetes.core.k8s:
      state: absent
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      api_version: kubevirt.io/v1alpha3
      kind: VirtualMachine
      name: upf-vm
      namespace: "{{ openshift.namespace }}"
