# 
# Deploy AMF
---
- hosts: localhost
  
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create AMF config map
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../..//templates/config/amf.yaml') | from_yaml }}"
  
  - name: Deploy AMF
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../..//templates/deployment/amf.yaml') | from_yaml }}"

  - name: Create AMF service
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../../templates/service/amf.yaml') | from_yaml }}"

