# 
# Deploy UDM
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create UDM config map
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../../templates/config/udm.yaml') | from_yaml }}"

  - name: Deploy UDM
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../../templates/deployment/udm.yaml') | from_yaml }}"

  - name: Create UDM service
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../../templates/service/udm.yaml') | from_yaml }}"
