# 
# Create namespace
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create namespace {{ openshift.namespace }}
    kubernetes.core.k8s:
      state: present
      name: "{{ openshift.namespace }}"
      host: "{{ openshift.api_url }}"
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      kind: Namespace
