# 
# Create bridge and attachment network for CNV
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create NodeNetworkConfigurationPolicy, br1 on worker nodes
    kubernetes.core.k8s:
      state: present
      apply: yes
      host: "{{ openshift.api_url }}"
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: nmstate.io/v1alpha1
        kind: NodeNetworkConfigurationPolicy
        metadata:
          name: bridge-br1
        spec:
          nodeSelector:
            node-role.kubernetes.io/worker: ''
          desiredState:
            interfaces:
              - name: br1
                description: Bridge with {{ openshift.host_ifname }} port
                type: linux-bridge
                state: up
                ipv4:
                  dhcp: true
                  enabled: true
                bridge:
                  options:
                    stp:
                      enabled: false
                  port:
                    - name: "{{ openshift.host_ifname }}"

  - name: Create NetworkAttachmentDefinition bridge-net 
    kubernetes.core.k8s:
      state: present
      apply: yes
      host: "{{ openshift.api_url }}" 
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: "k8s.cni.cncf.io/v1"
        kind: NetworkAttachmentDefinition
        metadata:
          name: bridge-net
          namespace: "{{ openshift.namespace }}"
          annotations:
            k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br1
        spec:
          config: '{
            "cniVersion": "0.3.1",
            "name": "bridge-net",
            "plugins": [
              {
                "type": "cnv-bridge",
                "bridge": "br1"
              },
              {
                "type": "cnv-tuning"
              }
            ]
          }'
