# 
# Create new network on OpenShift
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create namespace {{ openshift.namespace }}
    kubernetes.core.k8s:
      state: present
      name: "{{ openshift.namespace }}"
      host: "{{ openshift.api_url }}"
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      kind: Namespace

  - name: Create 5g-net network on the cluster
    kubernetes.core.k8s:
      state: present
      apply: yes
      host: "{{ openshift.api_url }}" 
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: operator.openshift.io/v1
        kind: Network
        metadata:
          name: cluster
        spec:
          additionalNetworks: 
          - name: 5g-net
            namespace: "{{ openshift.namespace }}"
            type: Raw
            rawCNIConfig: '{
              "cniVersion": "0.3.1",
              "name": "5g-net",
              "master": "br1",
              "type": "macvlan",
              "mode": "bridge",
              "ipam": {
                "type": "static"
              }
            }'
