# 
# Enable SCTP protocol on OpenShift
---
- hosts: localhost
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Enable SCTP protocol in master,worker nodes
    kubernetes.core.k8s:
      state: present
      apply: yes
      host: "{{ openshift.api_url }}"
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        metadata:
          labels:
            machineconfiguration.openshift.io/role: worker
            machineconfiguration.openshift.io/role: master
          name: 10-master-worker-load-sctp-module
        spec:
          config:
            ignition:
              version: 2.2.0
            storage:
              files:
                - contents:
                    source: data:,
                    verification: {}
                  filesystem: root
                  mode: 420
                  path: /etc/modprobe.d/sctp-blacklist.conf
                - contents:
                    source: data:text/plain;charset=utf-8,sctp
                  filesystem: root
                  mode: 420
                  path: /etc/modules-load.d/sctp-load.conf

  - name: Enable SCTP protocol in worker nodes
    kubernetes.core.k8s:
      state: present
      apply: yes
      host: "{{ openshift.api_url }}"
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      validate_certs: no
      definition:
        apiVersion: machineconfiguration.openshift.io/v1
        kind: MachineConfig
        metadata:
          labels:
            machineconfiguration.openshift.io/role: worker
          name: 10-worker-load-sctp-module
        spec:
          config:
            ignition:
              version: 2.2.0
            storage:
              files:
                - contents:
                    source: data:,
                    verification: {}
                  filesystem: root
                  mode: 420
                  path: /etc/modprobe.d/sctp-blacklist.conf
                - contents:
                    source: data:text/plain;charset=utf-8,sctp
                  filesystem: root
                  mode: 420
                  path: /etc/modules-load.d/sctp-load.conf
